language: python
python:
    - "3.6.5"

dist: trusty
sudo: rquired

services:
  - postgresql

before_script:
  - psql -c 'create database test_db;' -U postgres

env:
    - Django==2.1

install:
    - pip3 install -q -r requirements.txt

script:
    - ls -al
    - ls -al backend/
    - python3 backend/manage.py makemigrations
    - python3 backend/manage.py migrate
    - python3 -m pytest -n 3 --cov-config .coveragerc --cov=backend/