language: python
python:
    - "3.6.5"

dist: trusty
sudo: rquired

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

env:
    - Django==2.1

install:
    - pip3 install -q -r requirements.txt

script:
    - cd backend/backend
    - touch problem/secrets.py
    - python3 manage.py makemigrations
    - python3 manage.py migrate
    - python3 -m pytest -n 3 --cov-config .coveragerc --cov=backend/