language: python
python:
    - "3.6.5"

dist: trusty
sudo: rquired

env:
    - Django==2.1
    - djangorestframework==3.8.2

install:
    - pip3 install -q Django=$DJANGO_VERSION
    - pip3 install -q -r requirements.txt

script:
    - cd for_hg
    - touch problem/secrets.py
    - echo "AWS_ACCESS_KEY_ID=''" >> problem/secrets.py
    - echo "AWS_SECRET_ACCESS_KEY=''" >> problem/secrets.py
    - python3 manage.py migrate
    - python3 -m pytest -n 3 --cov-config .coveragerc --cov=.
