language: python
python:
    - "3.6.5"

dist: trusty
sudo: rquired

services:
    - postgresql

before_script:
    - psql -c 'create database test_db;' -U postgres

addons:
    postgresql: "9.6"
before_install:
    # stop old version
    - sudo /etc/init.d/postgresql stop
    # add postgresql 10 repository
    - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
    - sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs 2>/dev/null)-pgdg main" >> /etc/apt/sources.list.d/postgresql.list'
    # install new version
    - sudo apt-get update -qq
    - sudo apt-get install -qq postgresql-10 postgresql-client-10
    # clone auth config (might need to fix source path for another version)
    - sudo cp /etc/postgresql/9.6/main/pg_hba.conf /etc/postgresql/10/main/pg_hba.conf
    # start new version
    - sudo /etc/init.d/postgresql restart
    - export PGPORT=5433

env:
    - Django==2.1

install:
    - pip3 install -q -r backend/requirements.txt

script:
    - cd backend/
    - python3 manage.py makemigrations
    - python3 manage.py migrate
    - python3 -m pytest
